### ISSUE TITLE
None of the extractors get any hits.

### ISSUE THREAD

**Issue by doff-1** [greenmoss/pfsense_graylog#1]
This doesn't seem to work anymore, or it's a user fault on my side.
I'm using Graylog 4.1.0 and pfSense 2.5.2
I've found out it's made for pfSense sending the logs in RFC 3164 format. I was sending the logs in RFC 5424 format, but changing back to RFC 3164 doesn't make it work. 

None of the extractors get any hits.

What I've done so far is to create another input in graylog which only recieves data from pfsense. (rfc 5424)
Here I have applied the extractors, and made a couple of changes to pfsense-log data:
The regular expression is now ([^,]+,.+) and the condition is to always try to extract.

I wish the graylog extractor could have a condition on the application_name, so I wouldn't have to run this extractor on all messages from pfsense, but this seems to work. I know it's not a good solution but it's what I managed to do.

**Comment by doff-1** [comment]
I've improved my solution by having the input saving the full message, and making pfsense-log-data do the reg-ex on this instead.
^.*filterlog ..... - - (.*)$
I think it works like it should now, except that I use more space saving the full message in the indice.

**Comment by greenmoss** [comment]
Hello, thanks for the report! Can you send me a PR for the changes? Thanks again!

**Comment by greenmoss** [comment]
Closing this for now. If you can get me a PR I will re-open.
